### ISSUE TITLE
Separating classes in different files

### ISSUE THREAD

**Issue by Xanbertis** [Xanbertis/text_file_to_ui#6]
Each classes must be separated into its own file for compatibility with other compiling software among many other reasons.

**Comment by mislavmatijevic** [comment]
Wow. You work fast 😂

**Comment by Xanbertis** [comment]
> Wow. You work fast 😂

I'm making the changes as I read your reviews, I'll start pushing as soon as you're finished reading this first version 👍

**Comment by Xanbertis** [comment]
@mislavmatijevic I might be dumb and have referenced previous issues with my push comments instead of this one... they all follow the same syntax though so they shouldn't be too hard to spot, I also implemented the file access counter.
